spalojoki_dataplatform:
    target: prod
    outputs:
        prod:
            type: bigquery
            method: service-account
            project: "{{ env_var('GCP_PROJECT_ID') }}"
            dataset: analytics
            threads: 4
            keyfile: "{{ env_var('SAK_PATH') }}"